learning_rate: 0.00001
batch_size: 16
num_epochs: 200
weight_decay: 0.00001
num_classes: 1
img_size: 128
modality_type: "FMRI" #FMRI, T2W, DWI
random_seed: 42

#TODO: comment and uncomment the true dirs 

# dirs on my local
# images_dir: "/home/jhg307/codes/13_mia_hackathon/data/E2MIP_Challenge_FetalBrainSegmentation/data"
# test_data_dir: "/home/jhg307/codes/13_mia_hackathon/data/E2MIP_Challenge_FetalBrainSegmentation/data"
# test_save_path: '../test_volume_prediction'
# model_save_dir: "../trained_models"

# based on challenge instructions
images_dir: "/mnt/training_data"
test_data_dir: "/mnt/query_data"
test_save_path: '/mnt/predicted_data'
model_save_dir: "/mnt/training_results"
# How do we understand the above folder structure?
# in the above folders the training_data consists of the training data (we assume this contains training_slices and validation_slices),
# the training_results is where one would save the model weights (save the fine-tuned mobilenet here), 
# the query_data is the data to be predicted on aka the test set for us (we assume this contains test_volumes)
# and the predicted_data has the output of our predictions 